-- Create Routers Table
CREATE TABLE routers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    ip TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    autoConnect BOOLEAN DEFAULT false,
    lastConnected TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routerId TEXT NOT NULL,
    name TEXT NOT NULL,
    password TEXT,
    profile TEXT,
    address TEXT,
    comment TEXT,
    expiryTime TIMESTAMP WITH TIME ZONE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Usage History Table
CREATE TABLE usage_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routerId TEXT NOT NULL,
    userId TEXT,
    userName TEXT NOT NULL,
    bytesIn BIGINT DEFAULT 0,
    bytesOut BIGINT DEFAULT 0,
    loginTime TIMESTAMP WITH TIME ZONE,
    logoutTime TIMESTAMP WITH TIME ZONE,
    sessionDuration NUMERIC,
    status TEXT DEFAULT 'active',
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Login History Table
CREATE TABLE login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routerId TEXT NOT NULL,
    userName TEXT NOT NULL,
    ipAddress TEXT,
    macAddress TEXT,
    loginTime TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    logoutTime TIMESTAMP WITH TIME ZONE,
    status TEXT
);

-- Create Sales Table
CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routerId TEXT NOT NULL,
    voucherName TEXT NOT NULL,
    profile TEXT,
    price NUMERIC DEFAULT 0,
    soldAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(routerId, voucherName)
);

-- Create Settings Table
CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL
);

-- Turn off Row Level Security (RLS) for testing since this is a public dashboard without user auth
ALTER TABLE routers DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE login_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
